### ISSUE TITLE
Optionally add a hash of event content

### ISSUE THREAD

**Issue by smsiebe** [GEOINT/splunk-jul#1]
Allow, through API and config, an hash to be added to the log event data.

This would meet may similar STIG requirements -- an example of one:
Rule Title:   The DBMS must protect audit data records and integrity by using cryptographic mechanisms.
STIG ID: SRG-APP-000126-DB-000171  
Rule ID: SV-42739r1_rule 
Vuln ID: V-32402

**Comment by smsiebe** [comment]
fixed in 1e634a9706a0ea3ebb8807d8c555f57decd28bea

**Comment by iammyownalterego** [comment]
Nice!
